### PR TITLE
Update to latest OkHttp 3.12.1

### PR DESCRIPTION
**Pull request by tir38**
First off thanks for adding HTTPS support!

When switching to use that today I hit this OkHttp bug: https://github.com/square/okhttp/issues/4183. I see that it got fixed in OkHttp 3.12.0: https://github.com/square/okhttp/pull/4373 I'd like to have that update here as well so I can switch to HTTPS.

### CODE REVIEW

**Comment by tir38** [comment]
I fixed all the failing tests as a result of MockWebServer 3.10.0 -> 3.12.0. The 

The "delay" tests in io.appflate.restmock.RequestsChainTest are much more flaky w/ HTTPS.

When the tests do pass I'm getting these lint errors. Not sure if you want me to fix them in this PR:

```
Obsolete Gradle Dependency
../../build.gradle:63: A newer version of com.google.dagger:dagger than 2.15 is available: 2.19
  60     implementation "com.android.support:design:${supportVersion}"
  61     implementation "com.jakewharton:butterknife:8.8.1"
  62     annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
  63     implementation "com.google.dagger:dagger:2.15"                                                  
  64     implementation "com.squareup.retrofit2:retrofit:2.3.0"
  65     implementation "com.squareup.retrofit2:converter-gson:2.3.0"
  66     implementation "com.squareup.okhttp3:logging-interceptor:${okHttpVersion}"
../../build.gradle:64: A newer version of com.squareup.retrofit2:retrofit than 2.3.0 is available: 2.5.0
  61     implementation "com.jakewharton:butterknife:8.8.1"
  62     annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
  63     implementation "com.google.dagger:dagger:2.15"
  64     implementation "com.squareup.retrofit2:retrofit:2.3.0"                                          
  65     implementation "com.squareup.retrofit2:converter-gson:2.3.0"
  66     implementation "com.squareup.okhttp3:logging-interceptor:${okHttpVersion}"
  67     implementation "com.squareup.okhttp3:okhttp:${okHttpVersion}"
../../build.gradle:65: A newer version of com.squareup.retrofit2:converter-gson than 2.3.0 is available: 2.5.0
  62     annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
  63     implementation "com.google.dagger:dagger:2.15"
  64     implementation "com.squareup.retrofit2:retrofit:2.3.0"
  65     implementation "com.squareup.retrofit2:converter-gson:2.3.0"                                    
  66     implementation "com.squareup.okhttp3:logging-interceptor:${okHttpVersion}"
  67     implementation "com.squareup.okhttp3:okhttp:${okHttpVersion}"
../../build.gradle:72: A newer version of com.google.dagger:dagger-compiler than 2.15 is available: 2.19
  69     implementation "com.google.code.gson:gson:2.8.5"
  70     implementation "com.google.code.findbugs:annotations:2.0.3"
  71     compileOnly "javax.annotation:jsr250-api:1.0"
  72     annotationProcessor "com.google.dagger:dagger-compiler:2.15"                                    
  73 
  74     //Test dependencies
  75     androidTestImplementation "com.android.support.test:runner:1.0.2"
```

**Comment by tir38** [comment]
@andrzejchm let me know if you want me to fix those other Lint issues

**Comment by andrzejchm** [comment]
@tir38 if possible, please update the library versions to newest

**Comment by tir38** [comment]
@andrzejchm any chance on a 0.3.3 release w/ this fix? ;)

**Comment by andrzejchm** [comment]
definetely, expect the repease today

**Pull request merged**
