### PR TITLE
Add a RequestMatcher for determining if a path does not contain a string

### PR DESCRIPTION
**Pull request by jwir3**

### CODE REVIEW

**Comment by andrzejchm** [comment]
awesome! thanks for your input. Gonna merge it as soon as the build passes (seems like some connection problems on CircleCI)

**Comment by jwir3** [comment]
Of course. I have a couple of other things I'd like to get in, if possible, before the next release. I have a `RequestMatcher` for query parameters, as well as a `whenHEAD` method (my company uses this for one of our services, but it probably doesn't _need_ to go into RESTMock if you'd prefer it be limited to `GET`, `PUT`, POST`, `PATCH`, and `DELETE` requests).

I will get PRs for these up as soon as I get a chance (hopefully today).

**Comment by andrzejchm** [comment]
there is no reason of not adding a `HEAD` method for Request handlers, so Im looking forward for your changes :)

**Comment by andrzejchm** [comment]
in order to get rid of the lint error, please update your branch with the latest `develop` changes

**Pull request merged**
