### PR TITLE
Feature/when head

### PR DESCRIPTION
**Pull request by jwir3**

### CODE REVIEW

**Comment by jwir3** [comment]
So it seems to be showing that there are lint errors with these CircleCI checks, but I can't seem to reproduce them locally. :(

**Comment by andrzejchm** [comment]
https://109-56791509-gh.circle-artifacts.com/0//tmp/circle-artifacts.zXWVl5p/androidsample/outputs/lint-results-debug.html

It complains about the support library version. They are releasing way too often the new versions :D

**Comment by jwir3** [comment]
> It complains about the support library version. They are releasing way too often the new versions :D

Ah ok, I wasn't sure how to get to the build artifacts. Would you like me to update the support libraries in a new commit so Circle passes, or is that something you'll take care of?

**Comment by andrzejchm** [comment]
if you don't mind you could make a quick update please

**Comment by jwir3** [comment]
@andrzejchm Done. Hopefully that will fix the lint checks.

**Pull request merged**
