### PR TITLE
Update hamcrest to support espresso 3 4 0

### PR DESCRIPTION
**Pull request by oradkovsky**
New Espresso version brings hamcrest 2.2 which is not getting along with 1.3. This pr tries to solve the issue.

### CODE REVIEW

**Comment by andrzejchm** [comment]
awesome, thanks for the update @oradkovsky !

**Comment by Sloy** [comment]
Hi @andrzejchm! Any plans to release this PR soon?

**Comment by andrzejchm** [comment]
version 0.4.4 is now released and includes latest changes from this PR

**Comment by Sloy** [comment]
Thank you! You were faster publishing the new version than my build trying to use Jitpack 😂 

❤️

**Pull request merged**
