### PR TITLE
Add the ability to remove a mock using Matcher<RecordedRequest>

### PR DESCRIPTION
**Pull request by wellavelino**
There's two change here:

Added an overload to removeMatchableCall that takes a parameter `Matcher<RecordedRequest>`

whenRequested, now will remove the previously mock using the removeMatchableCall that takes requesteMatcher as a parameter.

This PR is linked to #86

### CODE REVIEW

**Comment by andrzejchm** [comment]
thanks for the pr. Could you write a unit test that prooves this works, when mock was created with different instance of the same matcher than the one used later on for removing, ie:
```
RESTMockServer.whenGET(pathEndsWith("users")).thenReturnFile("success_200.json")
RESTMockServer.removeMatchableCall(pathEndsWith("users"))
```

**Comment by wellavelino** [comment]
hey @andrzejchm sure, sorry that I didn't do this before.
I'll submit.

**Comment by MartyCatawiki** [comment]
Hi @wellavelino, i'm really looking forward to this feature, any time plan when you can finish this PR?

**Comment by andrzejchm** [comment]
your approach makes sense, the only problem I see here it might be pretty confusing for people. They might want to remove the calls the way I've posted above and think its a bug. A good approach here would be to make RequestMatchers override `equals` method to allow such approach

**Comment by andrzejchm** [comment]
I'll close this for now due to inactivity. Feel free to provide updates and reopen it when you feel its ready

**Pull request closed without merging**
